persons/urls.py
from django.urls import path
from .views import PersonsView, PersonCreate, PersonDetail, PersonUpdate, PersonDelete

urlpatterns = [
    path("", PersonsView.as_view(), name="persons"),
    path("ajouter/", PersonCreate.as_view(), name="person_add"),
    path("<int:pk>/", PersonDetail.as_view(), name="person_detail"),
    path("<int:pk>/modifier/", PersonUpdate.as_view(), name="person_update"),
    path("<int:pk>/supprimer/", PersonDelete.as_view(), name="person_delete"),
]

vla_django/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import HomeView
from infos.views import InfosView
from accounts.views import Signup, Signin, Logout


urlpatterns = [
    path("", HomeView.as_view(), name="index"),
    path("admin/", admin.site.urls),
    path("commandes/", include("commands.urls")),
    path("communication/", include("communication.urls")),
    path("groupes/", include("groups.urls")),
    path("infos/", InfosView.as_view(), name="infos"),
    path("ma_page/", include("private.urls")),
    path("personnes/", include("persons.urls")),
    path("predication/", include("predication.urls")),
    path("publications/", include("publications.urls")),
    path("vcm/", include("vcm.urls")),
    path("we/", include("we.urls")),
    path("inscription/", Signup.as_view(), name="signup"),
    path("connexion/", Signin.as_view(), name="signin"),
    path("deconnexion/", Logout.as_view(), name="logout"),
    path("notes/", include("notes.urls")),
]

we/urls.py
from django.urls import path
from .views import WeMeetingView, NewWeView, WeUpdate, WeDelete

urlpatterns = [
    path("", WeMeetingView.as_view(), name="we"),
    path("ajouter/", NewWeView.as_view(), name="new_we"),
    path("<int:pk>/modifier/", WeUpdate.as_view(), name="we_update"),
    path("<int:pk>/supprimer/", WeDelete.as_view(), name="we_delete"),
]

persons/models.py
from django.db import models
from groups.models import Group


class Role(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Person(models.Model):
    GENDER = (
        ("MALE", "Homme"),
        ("FEMALE", "Femme"),
    )

    FUNCTION = (
        ("NONE", ""),
        ("ELDER", "Ancien"),
        ("ASSISTANT", "Assistant"),
    )

    ROLES = (
        ("COORDINATOR", "Coordinateur"),
        ("SECRETARY", "Secrétaire"),
        ("PRED_RESP", "Responsable de la prédication"),
        ("GROUP_RESP", "Responsable de groupe"),
        ("GROUP_ADJ", "Adjoint de groupe"),
        ("GROUP_PREP", "Préposé de groupe"),
        ("TERR_RESP", "Responsable aux territoires"),
        ("TERR_ADJ", "Adjoint aux territoires"),
        ("BOOKS_RESP", "Responsable aux publications"),
        ("BOOKS_ADJ", "Adjoint aux publications"),
        ("CONSEILLOR", "Conseiller adjoint"),
        ("WATCHTOWER_RESP", "Responsable à la Tour de Garde"),
        ("VCM_RESP", "Responsable à la VCM"),
        ("VCM_ADJ", "Adjoint à la VCM"),
        ("WEEKEND_RESP", "Responsable des réunions du week-end"),
        ("WEEKEND_ADJ", "Adjoint aux réunions du week-end"),
        ("WELCOME_RESP", "Responsable de l'accueil"),
        ("WELCOME_MEMBER", "Membre de l'accueil"),
        ("SONO_RESP", "Responsable de la sono"),
        ("SONO_MEMBER", "Membre de la sono"),
        ("PODIUM", "Estrade"),
        ("MICRO", "Perche"),
        ("CLH", "CLH"),
        ("GESTION_RESP", "Responsable du Comité de gestion"),
        ("GESTION_MEMBER", "Membre du Comité de gestion"),
        ("MAINTENANCE_RESP", "Coordinateur à la maintenance"),
        ("CLEANING_RESP", "Coordinateur à l'entretien"),
        ("GREEN_SPACES_RESP", "Responsable des travaux d'espaces verts"),
        ("ACCOUNT_RESP", "Responsable aux comptes"),
        ("ACCOUNT_ADJ", "Adjoint aux comptes"),
        ("TREASURER", "Trésorier"),
        ("BOARD_RESP", "Responsable du tableau d'affichage"),
    )

    STATUS = (
        ("STUDENT", "Etudiant"),
        ("UNBAPT_PUBLISHER", "Proclamateur non baptisé"),
        ("PUBLISHER", "Proclamateur"),
        ("TEMPORARY", "Pionnier auxiliaire"),
        ("PERMANENT", "Pionnier permanent"),
        ("SPECIAL", "Pionnier spécial"),
    )

    firstname = models.CharField(
        max_length=100,
        verbose_name="Prénom",
    )
    lastname = models.CharField(
        max_length=100,
        verbose_name="Nom",
    )
    gender = models.CharField(
        max_length=6,
        choices=GENDER,
        verbose_name="Genre",
    )
    cong_function = models.CharField(
        max_length=9,
        choices=FUNCTION,
        verbose_name="Fonction",
        blank=True,
        null=True,
    )
    cong_roles = models.CharField(
        max_length=255,
        verbose_name="Rôles",
        blank=True,
        null=True,
    )
    cong_status = models.CharField(
        max_length=16,
        choices=STATUS,
        verbose_name="Statut",
        blank=True,
        null=True,
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        verbose_name="Groupe",
        blank=True,
        null=True,
    )

    def get_roles_display(self):
        roles = self.cong_roles.split(",")
        return [dict(self.ROLES).get(role.strip(), role.strip()) for role in roles]

    def get_roles_as_list(self):
        return self.cong_roles.split(",") if self.cong_roles else []

    @property
    def fullname(self):
        return f"{self.firstname} {self.lastname.upper()}"

    @property
    def roles_display_with_commas(self):
        roles_list = self.get_roles_display()
        return ", ".join(roles_list)

persons/forms.py
from django import forms
from persons.models import Person
from groups.models import Group

GENDER = (
    ("MALE", "Homme"),
    ("FEMALE", "Femme"),
)

FUNCTION = (
    ("NONE", ""),
    ("ELDER", "Ancien"),
    ("ASSISTANT", "Assistant"),
)

ROLES = (
    ("COORDINATOR", "Coordinateur"),
    ("SECRETARY", "Secrétaire"),
    ("PRED_RESP", "Responsable de la prédication"),
    ("GROUP_RESP", "Responsable de groupe"),
    ("GROUP_ADJ", "Adjoint de groupe"),
    ("GROUP_PREP", "Préposé de groupe"),
    ("TERR_RESP", "Responsable aux territoires"),
    ("TERR_ADJ", "Adjoint aux territoires"),
    ("BOOKS_RESP", "Responsable aux publications"),
    ("BOOKS_ADJ", "Adjoint aux publications"),
    ("CONSEILLOR", "Conseiller adjoint"),
    ("WATCHTOWER_RESP", "Responsable à la Tour de Garde"),
    ("VCM_RESP", "Responsable à la VCM"),
    ("VCM_ADJ", "Adjoint à la VCM"),
    ("WEEKEND_RESP", "Responsable des réunions du week-end"),
    ("WEEKEND_ADJ", "Adjoint aux réunions du week-end"),
    ("WELCOME_RESP", "Responsable de l'accueil"),
    ("WELCOME_MEMBER", "Membre de l'accueil"),
    ("SONO_RESP", "Responsable de la sono"),
    ("SONO_MEMBER", "Membre de la sono"),
    ("PODIUM", "Estrade"),
    ("MICRO", "Perche"),
    ("CLH", "CLH"),
    ("GESTION_RESP", "Responsable du Comité de gestion"),
    ("GESTION_MEMBER", "Membre du Comité de gestion"),
    ("MAINTENANCE_RESP", "Coordinateur à la maintenance"),
    ("CLEANING_RESP", "Coordinateur à l'entretien"),
    ("GREEN_SPACES_RESP", "Responsable des travaux d'espaces verts"),
    ("ACCOUNT_RESP", "Responsable aux comptes"),
    ("ACCOUNT_ADJ", "Adjoint aux comptes"),
    ("TREASURER", "Trésorier"),
    ("BOARD_RESP", "Responsable du tableau d'affichage"),
)

STATUS = (
    ("UNBAPT_PUBLISHER", "Proclamateur non baptisé"),
    ("PUBLISHER", "Proclamateur"),
    ("TEMPORARY", "Pionnier auxiliaire"),
    ("PERMANENT", "Pionnier permanent"),
    ("SPECIAL", "Pionnier spécial"),
)


class AddPerson(forms.Form):
    firstname = forms.CharField(
        required=True,
        max_length=100,
        label="Prénom",
        widget=forms.TextInput(
            attrs={
                "autofocus": "autofocus",
            }
        ),
    )
    lastname = forms.CharField(
        required=True,
        max_length=100,
        label="Nom",
    )
    gender = forms.ChoiceField(
        required=True,
        label="Genre",
        choices=Person.GENDER,
    )
    cong_function = forms.ChoiceField(
        required=True,
        label="Fonction",
        choices=Person.FUNCTION,
    )
    cong_roles = forms.MultipleChoiceField(
        required=False,
        label="Rôles",
        choices=sorted(Person.ROLES, key=lambda x: x[1]),
        widget=forms.CheckboxSelectMultiple,
    )
    cong_status = forms.ChoiceField(
        required=True,
        label="Statut",
        choices=Person.STATUS,
    )
    group = forms.ModelChoiceField(
        required=True,
        label="Groupe",
        queryset=Group.objects.all(),
    )

    def __init__(self, *args, **kwargs):
        initial = kwargs.get("initial", {})
        if "instance" in kwargs:
            instance = kwargs.pop("instance")
            initial["cong_roles"] = instance.get_roles_as_list()
        kwargs["initial"] = initial
        super().__init__(*args, **kwargs)

    def clean_cong_roles(self):
        roles = self.cleaned_data["cong_roles"]
        return ",".join(roles)

persons/views.py
from django.views import View
from django.views.generic import ListView, DetailView
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views import View
from django.shortcuts import redirect
from .models import Person
from .forms import AddPerson


def is_admin(user):
    return user.is_authenticated and hasattr(user, "is_admin") and user.is_admin


def is_nominated(user):
    return (
        user.is_authenticated
        and hasattr(user, "cong_function")
        and user.cong_function is not None
    )


class PersonsView(ListView):
    model = Person
    context_object_name = "persons"
    template_name = "persons/index.html"
    empty_text = "Aucun membre trouvé."
    ordering = ["lastname", "firstname"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["count"] = self.get_queryset().count()
        context["empty_text"] = self.empty_text

        return context


class PersonDetail(UserPassesTestMixin, DetailView):
    def test_func(self):
        return is_admin(self.request.user)

    def handle_no_permission(self):
        return redirect("persons")

    model = Person
    context_object_name = "person"
    template_name = "persons/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["role_display_list"] = self.object.get_roles_display()
        return context


class PersonCreate(UserPassesTestMixin, View):
    def test_func(self):
        return is_admin(self.request.user)

    def handle_no_permission(self):
        return redirect("persons")

    def get(self, request):
        form = AddPerson()
        submit_text = "Créer"
        title = "Créer un nouveau membre"

        return render(
            request,
            "persons/new.html",
            {
                "form": form,
                "title": title,
                "submit_text": submit_text,
            },
        )

    def post(self, request):
        form = AddPerson(request.POST)

        if form.is_valid():
            person_data = form.cleaned_data

            person = Person(
                firstname=person_data["firstname"],
                lastname=person_data["lastname"],
                gender=person_data["gender"],
                cong_function=person_data["cong_function"],
                cong_status=person_data["cong_status"],
                cong_roles=",".join(person_data["cong_roles"]),
                group=person_data["group"],
            )
            person.save()

            return render(
                request,
                "persons/new.html",
                {"form": AddPerson(), "success": "Membre ajouté avec succès."},
            )
        else:
            return render(
                request,
                "persons/new.html",
                {"form": form, "errors": form.errors},
            )

    def handle_no_permission(self):
        return redirect("persons")


class PersonUpdate(UserPassesTestMixin, View):
    def test_func(self):
        return is_admin(self.request.user)

    def handle_no_permission(self):
        return redirect("persons")

    def get(self, request, pk):
        person = Person.objects.get(pk=pk)
        title = f"Mise à jour de {person.firstname} {person.lastname}"
        submit_text = "Mettre à jour"

        form = AddPerson(
            initial={
                "firstname": person.firstname,
                "lastname": person.lastname,
                "gender": person.gender,
                "cong_function": person.cong_function,
                "cong_roles": person.cong_roles.split(","),
                "cong_status": person.cong_status,
                "group": person.group,
            }
        )

        return render(
            request,
            "persons/new.html",
            {
                "form": form,
                "title": title,
                "submit_text": submit_text,
            },
        )

    def post(self, request, pk):
        person = Person.objects.get(pk=pk)
        form = AddPerson(request.POST)

        if form.is_valid():
            person.firstname = form.cleaned_data["firstname"]
            person.lastname = form.cleaned_data["lastname"]
            person.gender = form.cleaned_data["gender"]
            person.cong_function = form.cleaned_data["cong_function"]
            person.cong_roles = form.cleaned_data["cong_roles"]
            person.cong_status = form.cleaned_data["cong_status"]
            person.group = form.cleaned_data["group"]
            person.save()

            return redirect("persons")

        return render(
            request,
            "persons/new.html",
            {
                "form": form,
                "errors": form.errors,
            },
        )


class PersonDelete(UserPassesTestMixin, View):
    def test_func(self):
        return is_admin(self.request.user)

    def handle_no_permission(self):
        return redirect("persons")

    def post(self, request, *args, **kwargs):
        pk = kwargs.get("pk")
        person = get_object_or_404(Person, pk=pk)
        person.delete()

        return redirect("persons")

persons/templates/persons/detail.html
{% extends 'vla_django/base.html' %} {% load static %} {% block extra_css %}
<link rel="stylesheet" href="{% static 'style/person_detail.css' %}" />
{% endblock %} {% block script_js %}
<script src="{% static 'js/person.js' %}"></script>
{% endblock %} {% block title %}VLA | Détail du membre{% endblock %} {% block content %}
<main>
  <h1>
    <a href="{% url 'persons' %}"
      ><img src="{% static 'icons/left_arrow.png' %}" alt="Retour"
    /></a>
    <span>Détail du membre de l'assemblée</span>
  </h1>

  <section>
    <article>
      <div>
        <span>Prénom :</span>
        <span>{{person.firstname}}</span>
      </div>

      <div>
        <span>Nom :</span>
        <span>{{person.lastname|upper}}</span>
      </div>

      <div>
        <span>Groupe :</span>
        <span>{{person.group}}</span>
      </div>

      <div>
        <span>Statut :</span>
        <span>{{person.get_cong_status_display}}</span>
      </div>

      <div>
        <span>Fonction :</span>
        <span>{{person.get_cong_function_display}}</span>
      </div>

      <div>
        <span>Rôles :</span>

        <ul>
          {% for role in role_display_list %}
          <li>{{ role }}</li>
          {% endfor %}
        </ul>
      </div>
    </article>

    <article>
      {% if person.gender == 'MALE' %}
      <img src="{% static 'icons/male_icon.png' %}" alt="male" />
      {% elif person.gender == 'FEMALE' %}
      <img src="{% static 'icons/female_icon.png' %}" alt="female" />
      {% endif %}
    </article>

    <article class="actions">
      <a href="{% url 'person_update' person.pk %}">Modifier</a>
      <form
        action="{% url 'person_delete' person.pk %}"
        method="post"
      >
        {% csrf_token %}
        <button type="submit">Supprimer</button>
      </form>
    </article>
  </section>
</main>
{% endblock %}

persons/templates/persons/index.html
{% extends 'vla_django/base.html' %} {% load static %} {% block extra_css %}
<link rel="stylesheet" href="{% static 'style/persons.css' %}" />
{% endblock %} {% block script_js %}
<script src="{% static 'js/persons.js' %}"></script>
{% endblock %} {% block title %}VLA | Membres{% endblock %} {% block content %}
<main>
  <h1>{{count}} membre{% if count > 1 %}s{% endif %}</h1>

  <a href="{% url 'person_add' %}">Créer un nouveau membre</a>

  <section>
    {% for person in persons %}
    <a
      href="{% url 'person_detail' person.pk %}"
      class="{{person.cong_function}}"
    >
      <span title="{{person.get_cong_status_display}}">
        {% if person.cong_status == "SPECIAL" %}
        <img src="{% static 'icons/star.png' %}" alt="étoile" />
        <img src="{% static 'icons/star.png' %}" alt="étoile" />
        <img src="{% static 'icons/star.png' %}" alt="étoile" />
        <br />
        {% elif person.cong_status == "PERMANENT" %}
        <img src="{% static 'icons/star.png' %}" alt="étoile" />
        <img src="{% static 'icons/star.png' %}" alt="étoile" />
        <br />
        {% elif person.cong_status == "TEMPORARY" %}
        <img src="{% static 'icons/star.png' %}" alt="étoile" />
        <br />
        {% endif %}
        {{person.firstname}}<br />{{person.lastname|upper}}
        <br />({{person.group}})
      </span>
    </a>
    {% empty %}
    <div>{{empty_text}}</div>
    {% endfor %}
  </section>
</main>
{% endblock %}

persons/templates/persons/new.html
{% extends 'vla_django/base.html' %} {% load static %} {% block extra_css %}
<link rel="stylesheet" href="{% static 'style/person_add.css' %}" />
{% endblock %} {% block script_js %}
<script src="{% static 'js/person_add.js' %}" defer></script>
{% endblock %} {% block title %}VLA | Nouveau membre{% endblock %} {% block content %}
<main>
  <h1>
    <a href="{% url 'persons' %}"
      ><img src="{% static 'icons/left_arrow.png' %}" alt="Retour"
    /></a>
    <span>
      {% if title %}
      {{title}}
      {% else %}
      Nouveau membre
      {% endif %}
    </span>
  </h1>

  <form method="POST">
    {% csrf_token %}
    <section>
      <div>{{ form.firstname.label_tag }} {{ form.firstname }}</div>
      <div>{{ form.lastname.label_tag }} {{ form.lastname }}</div>
      <div>{{ form.gender.label_tag }} {{ form.gender }}</div>
      <div>{{ form.cong_function.label_tag }} {{ form.cong_function }}</div>
      <div>{{ form.cong_status.label_tag }} {{ form.cong_status }}</div>
      <div>{{ form.group.label_tag }} {{ form.group }}</div>
      <div>{{ form.cong_roles.label_tag }} {{ form.cong_roles }}</div>
    </section>

    {% if form.non_field_errors %}
    <div class="error">{{ form.non_field_errors }}</div>
    {% endif %}

    <button type="submit">
      {% if submit_text %}
      {{submit_text}}
      {% else %}
      Valider
      {% endif %}
    </button>
  </form>
</main>
{% endblock %}

persons/templates/persons/old_update.html
{% extends 'vla_django/base.html' %} {% load static %} {% block extra_css %}
<link rel="stylesheet" href="{% static 'style/person_update.css' %}" />
{% endblock %} {% block script_js %}
<script src="{% static 'js/person_update.js' %}" defer></script>
{% endblock %} {% block title %}VLA | Modifier membre{% endblock %} {% include 'material/includes/material_css.html' %} {% load material_form %} {% block content %}
<main>
  <h1>
    <a href="{% url 'persons' %}"
      ><img src="{% static 'icons/left_arrow.png' %}" alt="Retour"
    /></a>
    <span>Modifier le membre</span>
  </h1>

  <form method="POST">
    {% csrf_token %}
    <section>
      <div>{{ form.firstname.label_tag }} {{ form.firstname }}</div>
      <div>{{ form.lastname.label_tag }} {{ form.lastname }}</div>
      <div>{{ form.gender.label_tag }} {{ form.gender }}</div>
      <div>{{ form.cong_function.label_tag }} {{ form.cong_function }}</div>
      <div>{{ form.cong_status.label_tag }} {{ form.cong_status }}</div>
      <div>{{ form.group.label_tag }} {{ form.group }}</div>
      <div>{{ form.cong_roles.label_tag }} {{ form.cong_roles }}</div>
    </section>

    <button type="submit">{{submit_text}}</button>
  </form>
</main>
{% endblock %}